/*
 Navicat Oracle Data Transfer

 Source Server         : ORCL
 Source Server Type    : Oracle
 Source Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 Source Host           : 172.20.95.207:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 File Encoding         : 65001

 Date: 24/12/2023 18:47:55
*/


-- ----------------------------
-- Table structure for BILL
-- ----------------------------
DROP TABLE "SCOTT"."BILL";
CREATE TABLE "SCOTT"."BILL" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "YEAR" VARCHAR2(4 BYTE) NOT NULL,
  "STATUS" NUMBER(1,0) NOT NULL,
  "PRICE" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BUILDING
-- ----------------------------
DROP TABLE "SCOTT"."BUILDING";
CREATE TABLE "SCOTT"."BUILDING" (
  "BID" VARCHAR2(50 BYTE) NOT NULL,
  "PWD" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CARD
-- ----------------------------
DROP TABLE "SCOTT"."CARD";
CREATE TABLE "SCOTT"."CARD" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "BID" VARCHAR2(50 BYTE) NOT NULL,
  "STATUS" NUMBER(1,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CHECKIN
-- ----------------------------
DROP TABLE "SCOTT"."CHECKIN";
CREATE TABLE "SCOTT"."CHECKIN" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "DID" VARCHAR2(100 BYTE),
  "STATUS" NUMBER(1,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CHECKOUT
-- ----------------------------
DROP TABLE "SCOTT"."CHECKOUT";
CREATE TABLE "SCOTT"."CHECKOUT" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "REASON" VARCHAR2(10 BYTE),
  "STATUS" NUMBER(1,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DORMITORY
-- ----------------------------
DROP TABLE "SCOTT"."DORMITORY";
CREATE TABLE "SCOTT"."DORMITORY" (
  "DID" VARCHAR2(100 BYTE) NOT NULL,
  "BID" VARCHAR2(50 BYTE) NOT NULL,
  "DOOR" VARCHAR2(50 BYTE) NOT NULL,
  "REMAIN" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FEE
-- ----------------------------
DROP TABLE "SCOTT"."FEE";
CREATE TABLE "SCOTT"."FEE" (
  "DID" VARCHAR2(100 BYTE) NOT NULL,
  "FEEDATE" DATE NOT NULL,
  "ELECTRICFEE" NUMBER NOT NULL,
  "WATERFEE" NUMBER NOT NULL,
  "STATUS" NUMBER(1,0) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LATE
-- ----------------------------
DROP TABLE "SCOTT"."LATE";
CREATE TABLE "SCOTT"."LATE" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "LATEDATE" DATE NOT NULL,
  "RECORDTIME" VARCHAR2(20 BYTE) NOT NULL,
  "REASON" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MAINTAIN
-- ----------------------------
DROP TABLE "SCOTT"."MAINTAIN";
CREATE TABLE "SCOTT"."MAINTAIN" (
  "ID" NUMBER NOT NULL,
  "DID" VARCHAR2(100 BYTE) NOT NULL,
  "ITEM" VARCHAR2(50 BYTE) NOT NULL,
  "REASON" VARCHAR2(50 BYTE),
  "PHONE" VARCHAR2(12 BYTE),
  "APPLYTIME" DATE NOT NULL,
  "HANDLETIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STUDENT
-- ----------------------------
DROP TABLE "SCOTT"."STUDENT";
CREATE TABLE "SCOTT"."STUDENT" (
  "STUDENTID" VARCHAR2(50 BYTE) NOT NULL,
  "DID" VARCHAR2(100 BYTE),
  "NAME" VARCHAR2(50 BYTE) NOT NULL,
  "GENDER" NUMBER(1,0) NOT NULL,
  "CLASSES" VARCHAR2(50 BYTE),
  "PWD" VARCHAR2(50 BYTE) NOT NULL,
  "STATUS" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- View structure for V_BUILDING_PEOPLE
-- ----------------------------
CREATE OR REPLACE VIEW "SCOTT"."V_BUILDING_PEOPLE" AS SELECT b.bid, count(*) AS amount FROM Building b, Card c WHERE c.bid=b.bid GROUP BY b.bid;

-- ----------------------------
-- View structure for V_DORMITORY_GENDER
-- ----------------------------
CREATE OR REPLACE VIEW "SCOTT"."V_DORMITORY_GENDER" AS SELECT 
d.did, 
avg(s.gender) AS gender, 
count(*) AS amount 
FROM Dormitory d, Student s 
WHERE s.did=d.did 
GROUP BY d.did
ORDER BY amount;

-- ----------------------------
-- Function structure for BILL_ADDINBATCH
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SCOTT"."BILL_ADDINBATCH" AS
BEGIN
FOR cur IN validSTU LOOP
INSERT INTO Bill VALUES(cur.studentid,y,0,p);
END LOOP;
END;
/

-- ----------------------------
-- Sequence structure for ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."ID_SEQ";
CREATE SEQUENCE "SCOTT"."ID_SEQ" MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Primary Key structure for table BILL
-- ----------------------------
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "PK_BILL" PRIMARY KEY ("STUDENTID", "YEAR");

-- ----------------------------
-- Checks structure for table BILL
-- ----------------------------
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "SYS_C0011802" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "SYS_C0011803" CHECK ("YEAR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "SYS_C0011804" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "SYS_C0011826" CHECK ("PRICE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table BILL
-- ----------------------------
CREATE TRIGGER "SCOTT"."ACCESS_INVALID" AFTER INSERT ON "SCOTT"."BILL" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (NEW.status=0) 
BEGIN
UPDATE Card SET status=0 WHERE studentid=:NEW.studentid;
END;
/
CREATE TRIGGER "SCOTT"."ACCESS_STATUS" AFTER UPDATE ON "SCOTT"."BILL" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (NEW.status=1) 
BEGIN
UPDATE Card SET status=1 WHERE studentid = :OLD.studentid;
END;
/

-- ----------------------------
-- Primary Key structure for table BUILDING
-- ----------------------------
ALTER TABLE "SCOTT"."BUILDING" ADD CONSTRAINT "SYS_C0011766" PRIMARY KEY ("BID");

-- ----------------------------
-- Checks structure for table BUILDING
-- ----------------------------
ALTER TABLE "SCOTT"."BUILDING" ADD CONSTRAINT "SYS_C0011764" CHECK ("BID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."BUILDING" ADD CONSTRAINT "SYS_C0011765" CHECK ("PWD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CARD
-- ----------------------------
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "SYS_C0011783" PRIMARY KEY ("STUDENTID");

-- ----------------------------
-- Checks structure for table CARD
-- ----------------------------
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "SYS_C0011780" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "SYS_C0011781" CHECK ("BID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "SYS_C0011782" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CHECKIN
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKIN" ADD CONSTRAINT "SYS_C0011792" PRIMARY KEY ("STUDENTID");

-- ----------------------------
-- Checks structure for table CHECKIN
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKIN" ADD CONSTRAINT "SYS_C0011790" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CHECKIN" ADD CONSTRAINT "SYS_C0011791" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CHECKOUT
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKOUT" ADD CONSTRAINT "SYS_C0011788" PRIMARY KEY ("STUDENTID");

-- ----------------------------
-- Checks structure for table CHECKOUT
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKOUT" ADD CONSTRAINT "SYS_C0011786" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CHECKOUT" ADD CONSTRAINT "SYS_C0011787" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DORMITORY
-- ----------------------------
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "SYS_C0011771" PRIMARY KEY ("DID");

-- ----------------------------
-- Checks structure for table DORMITORY
-- ----------------------------
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "SYS_C0011767" CHECK ("DID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "SYS_C0011768" CHECK ("BID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "SYS_C0011769" CHECK ("DOOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "SYS_C0011770" CHECK ("REMAIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FEE
-- ----------------------------
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "PK_FEE" PRIMARY KEY ("DID", "FEEDATE");

-- ----------------------------
-- Checks structure for table FEE
-- ----------------------------
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "SYS_C0011828" CHECK ("DID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "SYS_C0011829" CHECK ("FEEDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "SYS_C0011830" CHECK ("ELECTRICFEE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "SYS_C0011831" CHECK ("WATERFEE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "SYS_C0011832" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LATE
-- ----------------------------
ALTER TABLE "SCOTT"."LATE" ADD CONSTRAINT "PK_LATE" PRIMARY KEY ("STUDENTID", "LATEDATE");

-- ----------------------------
-- Checks structure for table LATE
-- ----------------------------
ALTER TABLE "SCOTT"."LATE" ADD CONSTRAINT "SYS_C0011862" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."LATE" ADD CONSTRAINT "SYS_C0011863" CHECK ("LATEDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."LATE" ADD CONSTRAINT "SYS_C0011864" CHECK ("RECORDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MAINTAIN
-- ----------------------------
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "SYS_C0011799" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MAINTAIN
-- ----------------------------
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "SYS_C0011795" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "SYS_C0011796" CHECK ("DID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "SYS_C0011797" CHECK ("ITEM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "SYS_C0011798" CHECK ("APPLYTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table MAINTAIN
-- ----------------------------
CREATE TRIGGER "SCOTT"."ID_SEQ_TRG" BEFORE INSERT ON "SCOTT"."MAINTAIN" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (NEW.id IS NULL) 
BEGIN
  SELECT ID_SEQ.NEXTVAL
  INTO :NEW.id
  FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table STUDENT
-- ----------------------------
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011778" PRIMARY KEY ("STUDENTID");

-- ----------------------------
-- Checks structure for table STUDENT
-- ----------------------------
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011773" CHECK ("STUDENTID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011774" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011775" CHECK ("GENDER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011776" CHECK ("PWD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "SYS_C0011777" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table STUDENT
-- ----------------------------
CREATE TRIGGER "SCOTT"."CHANGE_DID" AFTER UPDATE OF "DID" ON "SCOTT"."STUDENT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
UPDATE CheckIn SET did=:NEW.did WHERE studentid=:OLD.studentid;
END;
/

-- ----------------------------
-- Foreign Keys structure for table BILL
-- ----------------------------
ALTER TABLE "SCOTT"."BILL" ADD CONSTRAINT "FK_BILL" FOREIGN KEY ("STUDENTID") REFERENCES "SCOTT"."STUDENT" ("STUDENTID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CARD
-- ----------------------------
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "FK_CARD_BID" FOREIGN KEY ("BID") REFERENCES "SCOTT"."BUILDING" ("BID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CARD" ADD CONSTRAINT "FK_CARD_ID" FOREIGN KEY ("STUDENTID") REFERENCES "SCOTT"."STUDENT" ("STUDENTID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CHECKIN
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKIN" ADD CONSTRAINT "FK_CHECKIN" FOREIGN KEY ("STUDENTID") REFERENCES "SCOTT"."STUDENT" ("STUDENTID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."CHECKIN" ADD CONSTRAINT "FK_CHECKIN_DID" FOREIGN KEY ("DID") REFERENCES "SCOTT"."DORMITORY" ("DID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CHECKOUT
-- ----------------------------
ALTER TABLE "SCOTT"."CHECKOUT" ADD CONSTRAINT "FK_CHECKOUT" FOREIGN KEY ("STUDENTID") REFERENCES "SCOTT"."STUDENT" ("STUDENTID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table DORMITORY
-- ----------------------------
ALTER TABLE "SCOTT"."DORMITORY" ADD CONSTRAINT "FK_DORMITORY" FOREIGN KEY ("BID") REFERENCES "SCOTT"."BUILDING" ("BID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FEE
-- ----------------------------
ALTER TABLE "SCOTT"."FEE" ADD CONSTRAINT "FK_FEE" FOREIGN KEY ("DID") REFERENCES "SCOTT"."DORMITORY" ("DID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table LATE
-- ----------------------------
ALTER TABLE "SCOTT"."LATE" ADD CONSTRAINT "FK_LATE" FOREIGN KEY ("STUDENTID") REFERENCES "SCOTT"."STUDENT" ("STUDENTID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table MAINTAIN
-- ----------------------------
ALTER TABLE "SCOTT"."MAINTAIN" ADD CONSTRAINT "FK_MAINTAIN" FOREIGN KEY ("DID") REFERENCES "SCOTT"."DORMITORY" ("DID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table STUDENT
-- ----------------------------
ALTER TABLE "SCOTT"."STUDENT" ADD CONSTRAINT "FK_STUDENT" FOREIGN KEY ("DID") REFERENCES "SCOTT"."DORMITORY" ("DID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
